/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TajweedRouteImport } from './routes/tajweed'
import { Route as SunnahRouteImport } from './routes/sunnah'
import { Route as SebhaRouteImport } from './routes/sebha'
import { Route as QuranRouteImport } from './routes/quran'
import { Route as QiblaRouteImport } from './routes/qibla'
import { Route as PrayerTimesRouteImport } from './routes/prayer-times'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as HadithRouteImport } from './routes/hadith'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AthkarRouteImport } from './routes/athkar'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuranIndexRouteImport } from './routes/quran.index'
import { Route as QuranSurahRouteImport } from './routes/quran.$surah'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const TajweedRoute = TajweedRouteImport.update({
  id: '/tajweed',
  path: '/tajweed',
  getParentRoute: () => rootRouteImport,
} as any)
const SunnahRoute = SunnahRouteImport.update({
  id: '/sunnah',
  path: '/sunnah',
  getParentRoute: () => rootRouteImport,
} as any)
const SebhaRoute = SebhaRouteImport.update({
  id: '/sebha',
  path: '/sebha',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranRoute = QuranRouteImport.update({
  id: '/quran',
  path: '/quran',
  getParentRoute: () => rootRouteImport,
} as any)
const QiblaRoute = QiblaRouteImport.update({
  id: '/qibla',
  path: '/qibla',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerTimesRoute = PrayerTimesRouteImport.update({
  id: '/prayer-times',
  path: '/prayer-times',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const HadithRoute = HadithRouteImport.update({
  id: '/hadith',
  path: '/hadith',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AthkarRoute = AthkarRouteImport.update({
  id: '/athkar',
  path: '/athkar',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranIndexRoute = QuranIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuranRoute,
} as any)
const QuranSurahRoute = QuranSurahRouteImport.update({
  id: '/$surah',
  path: '/$surah',
  getParentRoute: () => QuranRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assistant': typeof AssistantRoute
  '/athkar': typeof AthkarRoute
  '/contact': typeof ContactRoute
  '/hadith': typeof HadithRoute
  '/learn': typeof LearnRoute
  '/prayer-times': typeof PrayerTimesRoute
  '/qibla': typeof QiblaRoute
  '/quran': typeof QuranRouteWithChildren
  '/sebha': typeof SebhaRoute
  '/sunnah': typeof SunnahRoute
  '/tajweed': typeof TajweedRoute
  '/api/chat': typeof ApiChatRoute
  '/quran/$surah': typeof QuranSurahRoute
  '/quran/': typeof QuranIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assistant': typeof AssistantRoute
  '/athkar': typeof AthkarRoute
  '/contact': typeof ContactRoute
  '/hadith': typeof HadithRoute
  '/learn': typeof LearnRoute
  '/prayer-times': typeof PrayerTimesRoute
  '/qibla': typeof QiblaRoute
  '/sebha': typeof SebhaRoute
  '/sunnah': typeof SunnahRoute
  '/tajweed': typeof TajweedRoute
  '/api/chat': typeof ApiChatRoute
  '/quran/$surah': typeof QuranSurahRoute
  '/quran': typeof QuranIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assistant': typeof AssistantRoute
  '/athkar': typeof AthkarRoute
  '/contact': typeof ContactRoute
  '/hadith': typeof HadithRoute
  '/learn': typeof LearnRoute
  '/prayer-times': typeof PrayerTimesRoute
  '/qibla': typeof QiblaRoute
  '/quran': typeof QuranRouteWithChildren
  '/sebha': typeof SebhaRoute
  '/sunnah': typeof SunnahRoute
  '/tajweed': typeof TajweedRoute
  '/api/chat': typeof ApiChatRoute
  '/quran/$surah': typeof QuranSurahRoute
  '/quran/': typeof QuranIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/assistant'
    | '/athkar'
    | '/contact'
    | '/hadith'
    | '/learn'
    | '/prayer-times'
    | '/qibla'
    | '/quran'
    | '/sebha'
    | '/sunnah'
    | '/tajweed'
    | '/api/chat'
    | '/quran/$surah'
    | '/quran/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/assistant'
    | '/athkar'
    | '/contact'
    | '/hadith'
    | '/learn'
    | '/prayer-times'
    | '/qibla'
    | '/sebha'
    | '/sunnah'
    | '/tajweed'
    | '/api/chat'
    | '/quran/$surah'
    | '/quran'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/assistant'
    | '/athkar'
    | '/contact'
    | '/hadith'
    | '/learn'
    | '/prayer-times'
    | '/qibla'
    | '/quran'
    | '/sebha'
    | '/sunnah'
    | '/tajweed'
    | '/api/chat'
    | '/quran/$surah'
    | '/quran/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AssistantRoute: typeof AssistantRoute
  AthkarRoute: typeof AthkarRoute
  ContactRoute: typeof ContactRoute
  HadithRoute: typeof HadithRoute
  LearnRoute: typeof LearnRoute
  PrayerTimesRoute: typeof PrayerTimesRoute
  QiblaRoute: typeof QiblaRoute
  QuranRoute: typeof QuranRouteWithChildren
  SebhaRoute: typeof SebhaRoute
  SunnahRoute: typeof SunnahRoute
  TajweedRoute: typeof TajweedRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tajweed': {
      id: '/tajweed'
      path: '/tajweed'
      fullPath: '/tajweed'
      preLoaderRoute: typeof TajweedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sunnah': {
      id: '/sunnah'
      path: '/sunnah'
      fullPath: '/sunnah'
      preLoaderRoute: typeof SunnahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sebha': {
      id: '/sebha'
      path: '/sebha'
      fullPath: '/sebha'
      preLoaderRoute: typeof SebhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran': {
      id: '/quran'
      path: '/quran'
      fullPath: '/quran'
      preLoaderRoute: typeof QuranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qibla': {
      id: '/qibla'
      path: '/qibla'
      fullPath: '/qibla'
      preLoaderRoute: typeof QiblaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer-times': {
      id: '/prayer-times'
      path: '/prayer-times'
      fullPath: '/prayer-times'
      preLoaderRoute: typeof PrayerTimesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hadith': {
      id: '/hadith'
      path: '/hadith'
      fullPath: '/hadith'
      preLoaderRoute: typeof HadithRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athkar': {
      id: '/athkar'
      path: '/athkar'
      fullPath: '/athkar'
      preLoaderRoute: typeof AthkarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran/': {
      id: '/quran/'
      path: '/'
      fullPath: '/quran/'
      preLoaderRoute: typeof QuranIndexRouteImport
      parentRoute: typeof QuranRoute
    }
    '/quran/$surah': {
      id: '/quran/$surah'
      path: '/$surah'
      fullPath: '/quran/$surah'
      preLoaderRoute: typeof QuranSurahRouteImport
      parentRoute: typeof QuranRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface QuranRouteChildren {
  QuranSurahRoute: typeof QuranSurahRoute
  QuranIndexRoute: typeof QuranIndexRoute
}

const QuranRouteChildren: QuranRouteChildren = {
  QuranSurahRoute: QuranSurahRoute,
  QuranIndexRoute: QuranIndexRoute,
}

const QuranRouteWithChildren = QuranRoute._addFileChildren(QuranRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AssistantRoute: AssistantRoute,
  AthkarRoute: AthkarRoute,
  ContactRoute: ContactRoute,
  HadithRoute: HadithRoute,
  LearnRoute: LearnRoute,
  PrayerTimesRoute: PrayerTimesRoute,
  QiblaRoute: QiblaRoute,
  QuranRoute: QuranRouteWithChildren,
  SebhaRoute: SebhaRoute,
  SunnahRoute: SunnahRoute,
  TajweedRoute: TajweedRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
